### ISSUE TITLE
Encounter error IOClient isn't supported on this platform.

### ISSUE THREAD

**Issue by aquariusbox** [Pajn/ElasticDart#1]
When use this library in client side.
Encounter IOClient isn't supported on this platform. 

Stack Trace:
#0      assertSupported (package:http/src/io.dart:34:3)
#1      Client.Client (package:http/src/client.dart:34:5)
#2      BaseRequest.send (package:http/src/base_request.dart:115:22)
#3      ElasticRequest._request.<_request_async_body> (package:elastic_dart/src/elastic_request.dart:24:34)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#5      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#6      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#7      _ScheduleImmediateHelper._handleMutation (dart:html:42407)

Any option to allow to change http using brower_client?
import 'package:http/browser_client.dart' as http;

**Comment by Pajn** [comment]
Good idea, should be possible

**Comment by Pajn** [comment]
Does ab982ab273a946653a014ca60d00a7cd8c156313 solve your use case? If so I'll go ahead and publish it.

**Comment by aquariusbox** [comment]
Yes, great to see this change.
